const DEFAULT_API_BASE = 'http://localhost:8787';
const DEFAULT_STATE = { savedTools: [], userPreferences: { defaultFilters: {}, dismissedNotifications: [], privacyAcknowledged: false, automaticDetectionEnabled: true }, latestRecommendations: [], unread: false, tabDomains: {}, localRecommendationCache: {} };
const TIER1_DOMAINS = [
  ['mail.google.com','email management'], ['outlook.live.com','email management'], ['outlook.office.com','email management'], ['gmail.com','email management'],
  ['docs.google.com','document editing'], ['office.com','document editing'], ['notion.so','document editing'], ['dropbox.com','document editing'],
  ['figma.com','design'], ['canva.com','design'], ['adobe.com','design'], ['github.com','coding'], ['gitlab.com','coding'], ['stackoverflow.com','coding'],
  ['calendar.google.com','meetings'], ['zoom.us','meetings'], ['meet.google.com','meetings'], ['teams.microsoft.com','meetings'], ['slack.com','productivity'],
  ['trello.com','project management'], ['asana.com','project management'], ['jira','project management'], ['salesforce.com','sales'], ['hubspot.com','sales'],
  ['zapier.com','automation'], ['make.com','automation'], ['airtable.com','data analysis'], ['sheets.google.com','data analysis'], ['analytics.google.com','data analysis'],
  ['youtube.com','video creation'], ['vimeo.com','video creation'], ['linkedin.com','marketing'], ['x.com','marketing'], ['twitter.com','marketing'], ['medium.com','writing'], ['wordpress.com','writing'], ['webflow.com','website building'], ['shopify.com','ecommerce'], ['amazon.com','ecommerce'], ['coursera.org','learning'], ['udemy.com','learning'], ['perplexity.ai','research']
];
const PROMPTS = { 'email management': ['Help me filter important emails', 'Draft a concise reply', 'Summarize this inbox workflow'], coding: ['Help me debug this code', 'Suggest tests for this change', 'Explain this repository workflow'], design: ['Create a design concept', 'Improve this visual asset', 'Find a tool for brand graphics'], 'document editing': ['Summarize this document', 'Improve this draft', 'Turn notes into an outline'], meetings: ['Summarize meeting notes', 'Extract action items', 'Prepare a meeting agenda'], automation: ['Automate this repetitive workflow', 'Connect these apps', 'Suggest a no-code automation'], research: ['Research this topic with sources', 'Compare tools for this task', 'Find credible references'], productivity: ['Recommend an AI productivity tool', 'Help organize this workflow', 'Find a simpler way to do this'] };
async function storageGet(keys) { return chrome.storage.sync.get(keys); }
async function storageSet(values) { return chrome.storage.sync.set(values); }
async function localSet(values) { return chrome.storage.local.set(values); }
async function localGet(keys) { return chrome.storage.local.get(keys); }
async function ensureState() { const sync = await storageGet(['savedTools', 'userPreferences']); const local = await localGet(['latestRecommendations', 'latestClassification', 'unread', 'tabDomains', 'localRecommendationCache']); return { ...DEFAULT_STATE, ...sync, ...local, userPreferences: { ...DEFAULT_STATE.userPreferences, ...(sync.userPreferences || {}) } }; }
async function userId() { const { slopUserId } = await chrome.storage.local.get('slopUserId'); if (slopUserId) return slopUserId; const id = crypto.randomUUID(); await chrome.storage.local.set({ slopUserId: id }); return id; }
async function apiBase() { return (await chrome.storage.local.get('slopApiBase')).slopApiBase || DEFAULT_API_BASE; }
async function api(path, body) { const response = await fetch(`${await apiBase()}${path}`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-user-id': await userId(), 'x-slop-token': (await chrome.storage.local.get('slopApiToken')).slopApiToken || '' }, body: JSON.stringify(body || {}) }); if (!response.ok) throw new Error((await response.json()).error || `API ${response.status}`); return response.json(); }
async function apiGet(path) { const response = await fetch(`${await apiBase()}${path}`, { headers: { 'x-user-id': await userId(), 'x-slop-token': (await chrome.storage.local.get('slopApiToken')).slopApiToken || '' } }); if (!response.ok) throw new Error(`API ${response.status}`); return response.json(); }
function topDomain(rawUrl = '') { try { return new URL(rawUrl).hostname.replace(/^www\./, ''); } catch { return ''; } }
function normalizedCacheKey(payload, category) { try { const url = new URL(payload.url); return `${url.hostname.replace(/^www\./,'')}/${url.pathname.split('/').filter(Boolean)[0] || ''}::${category}::${(payload.task || '').toLowerCase().trim()}`; } catch { return `manual::${category}::${(payload.task || '').toLowerCase().trim()}`; } }
function tier1Classify(url = '') { const normalized = url.toLowerCase(); const match = TIER1_DOMAINS.find(([pattern]) => normalized.includes(pattern)); return match && { tier: 1, taskCategory: match[1], prompts: PROMPTS[match[1]] || PROMPTS.productivity }; }
async function collectTabContext(tab) { return { url: tab?.url || '', title: tab?.title || '', metaDescription: '' }; }
async function requestRecommendations(payload, unread = true) { const state = await ensureState(); const result = await api('/recommendations', { ...payload, savedTools: state.savedTools }); await localSet({ latestRecommendations: result.recommendations, latestClassification: { tier: result.tier, taskCategory: result.taskCategory, prompts: result.prompts, cacheHit: result.cacheHit }, unread, localRecommendationCache: { ...state.localRecommendationCache, [normalizedCacheKey(payload, result.taskCategory)]: { recommendations: result.recommendations, classification: { tier: result.tier, taskCategory: result.taskCategory, prompts: result.prompts, cacheHit: true }, cachedAt: Date.now() } } }); await emit('recommendations_shown', { taskCategory: result.taskCategory, metadata: { tier: result.tier, cacheHit: result.cacheHit } }); if (unread) await emit('notification_badge_shown', { taskCategory: result.taskCategory }); for (const tool of result.recommendations || []) if (tool.alreadySaved) await emit('saved_tool_surfaced', { toolId: tool.id, taskCategory: result.taskCategory }); return result; }
async function runAutomaticDetection(tab) { if (!tab?.id || !tab?.url || tab.url.startsWith('chrome://')) return; const state = await ensureState(); if (!state.userPreferences.privacyAcknowledged || !state.userPreferences.automaticDetectionEnabled) return; const domain = topDomain(tab.url); const previous = state.tabDomains[String(tab.id)]; if (!domain || previous === domain) return; await localSet({ tabDomains: { ...state.tabDomains, [String(tab.id)]: domain } }); setTimeout(async () => { const context = await collectTabContext(tab); await emit('detection_started', { url: context.url }); const localClassification = tier1Classify(context.url); if (localClassification) { const cached = state.localRecommendationCache[normalizedCacheKey(context, localClassification.taskCategory)]; if (cached?.recommendations?.length) { await localSet({ latestRecommendations: cached.recommendations, latestClassification: cached.classification, unread: true }); await emit('recommendations_shown', { taskCategory: localClassification.taskCategory, metadata: { tier: 1, cacheHit: true, source: 'client' } }); await emit('notification_badge_shown', { taskCategory: localClassification.taskCategory }); return; } await requestRecommendations({ ...context, ...localClassification }, true); return; } const cache = await api('/cache/check', context); if (cache.cacheHit && cache.recommendations?.length) { await localSet({ latestRecommendations: cache.recommendations, latestClassification: { tier: cache.tier, taskCategory: cache.taskCategory, prompts: cache.prompts, cacheHit: true }, unread: true }); await emit('recommendations_shown', { taskCategory: cache.taskCategory, metadata: { tier: cache.tier, cacheHit: true } }); await emit('notification_badge_shown', { taskCategory: cache.taskCategory }); return; } await requestRecommendations(context, true); }, 4000); }
async function emit(eventType, body = {}) { return api('/events', { eventType, ...body }).catch(() => undefined); }
chrome.runtime.onInstalled.addListener(async () => { const state = await ensureState(); await storageSet({ savedTools: state.savedTools, userPreferences: state.userPreferences }); });
chrome.tabs.onUpdated.addListener((_tabId, changeInfo, tab) => { if (changeInfo.status === 'complete') runAutomaticDetection(tab); });
chrome.action.onClicked.addListener(async (tab) => { if (tab?.id) chrome.tabs.sendMessage(tab.id, { type: 'SLOP_TOGGLE' }).catch(() => undefined); });
chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => { (async () => {
  if (message.type === 'SLOP_GET_STATE') return { state: await ensureState(), apiBase: await apiBase() };
  if (message.type === 'SLOP_ACK_PRIVACY') { const state = await ensureState(); const userPreferences = { ...state.userPreferences, privacyAcknowledged: true }; await storageSet({ userPreferences }); await emit('privacy_acknowledged'); return { userPreferences }; }
  if (message.type === 'SLOP_MANUAL_RECOMMEND') { await emit(message.fromPrompt ? 'suggested_prompt_submitted' : 'manual_task_submitted'); return await requestRecommendations({ task: message.task, url: message.url, title: message.title, metaDescription: message.metaDescription || '' }, false); }
  if (message.type === 'SLOP_ADVANCED_RECOMMEND') { await emit('advanced_task_submitted'); return await requestRecommendations({ task: `${message.task}\nOutcome: ${message.outcome}\nCurrent tool: ${message.currentTool}\nConstraints: ${message.constraints}`, url: message.url, title: message.title, metaDescription: message.metaDescription || '' }, false); }
  if (message.type === 'SLOP_INSTALL_GUIDE') { await emit('proceed_clicked', { toolId: message.toolId }); return await api('/install-guide', { toolId: message.toolId, task: message.task }); }
  if (message.type === 'SLOP_SAVE_TOOL') { const state = await ensureState(); const savedTools = [...state.savedTools.filter(t => t.toolId !== message.toolId), { toolId: message.toolId, dateAdded: new Date().toISOString(), sourceTaskCategory: message.taskCategory || 'manual' }]; await storageSet({ savedTools }); await emit('download_confirmed', { toolId: message.toolId, taskCategory: message.taskCategory }); return { savedTools }; }
  if (message.type === 'SLOP_CLEAR_SAVED') { await storageSet({ savedTools: [] }); return { savedTools: [] }; }
  if (message.type === 'SLOP_RESET_DATA') { await storageSet({ savedTools: [], userPreferences: DEFAULT_STATE.userPreferences }); await localSet({ latestRecommendations: [], latestClassification: null, unread: false, localRecommendationCache: {}, slopUserId: crypto.randomUUID() }); await emit('user_data_reset'); return { ok: true }; }
  if (message.type === 'SLOP_SET_FILTERS') { const state = await ensureState(); const userPreferences = { ...state.userPreferences, defaultFilters: message.filters || {} }; await storageSet({ userPreferences }); await emit('filter_used'); return { userPreferences }; }
  if (message.type === 'SLOP_MARK_READ') { await localSet({ unread: false }); await emit('notification_opened'); return { unread: false }; }
  if (message.type === 'SLOP_CARD_CLICKED') { await emit('card_clicked', { toolId: message.toolId }); await emit('detail_opened', { toolId: message.toolId }); if (message.alreadySaved) await emit('saved_tool_clicked', { toolId: message.toolId }); return { ok: true }; }
  if (message.type === 'SLOP_EVENT') { await emit(message.eventType, message.body || {}); return { ok: true }; }
  if (message.type === 'SLOP_SET_AUTOMATIC_DETECTION') { const state = await ensureState(); const userPreferences = { ...state.userPreferences, automaticDetectionEnabled: Boolean(message.enabled) }; await storageSet({ userPreferences }); return { userPreferences }; }
  if (message.type === 'SLOP_SET_API_BASE') { await chrome.storage.local.set({ slopApiBase: message.apiBase || DEFAULT_API_BASE }); return { apiBase: await apiBase() }; }
  if (message.type === 'SLOP_OPEN_TOOL') { await chrome.tabs.create({ url: message.url }); return { ok: true }; }
  return { error: 'Unknown message' };
})().then(sendResponse).catch(error => sendResponse({ error: error.message })); return true; });
