const DEFAULT_API_BASE = 'http://localhost:8787';
const DEFAULT_STATE = { savedTools: [], userPreferences: { defaultFilters: {}, dismissedNotifications: [], privacyAcknowledged: false, automaticDetectionEnabled: true }, latestRecommendations: [], unread: false, tabDomains: {}, localRecommendationCache: {} };
const TIER1_DOMAINS = [
  ['mail.google.com','email management'], ['outlook.live.com','email management'], ['outlook.office.com','email management'], ['gmail.com','email management'],
  ['docs.google.com','document editing'], ['office.com','document editing'], ['notion.so','document editing'], ['dropbox.com','document editing'],
  ['figma.com','design'], ['canva.com','design'], ['adobe.com','design'], ['github.com','coding'], ['gitlab.com','coding'], ['stackoverflow.com','coding'],
  ['calendar.google.com','meetings'], ['zoom.us','meetings'], ['meet.google.com','meetings'], ['teams.microsoft.com','meetings'], ['slack.com','productivity'],
  ['trello.com','project management'], ['asana.com','project management'], ['jira','project management'], ['salesforce.com','sales'], ['hubspot.com','sales'],
  ['zapier.com','automation'], ['make.com','automation'], ['airtable.com','data analysis'], ['sheets.google.com','data analysis'], ['analytics.google.com','data analysis'],
  ['youtube.com','video creation'], ['vimeo.com','video creation'], ['linkedin.com','marketing'], ['x.com','marketing'], ['twitter.com','marketing'], ['medium.com','writing'], ['wordpress.com','writing'], ['webflow.com','website building'], ['shopify.com','ecommerce'], ['amazon.com','ecommerce'], ['coursera.org','learning'], ['udemy.com','learning'], ['perplexity.ai','research']
];

const FALLBACK_TOOLS = [
  { id: 'chatgpt', name: 'ChatGPT', description: 'General-purpose assistant for writing, coding, research, email, and productivity tasks.', rating: 4.8, userCount: 180000000, costTier: 'Freemium', complexityTier: 'Beginner', url: 'https://chatgpt.com', categories: ['writing','research','coding','productivity','email management','document editing'], installSteps: ['Open ChatGPT.','Sign in or create an account.','Describe your task and constraints.','Review and adapt the output.'] },
  { id: 'claude', name: 'Claude', description: 'Long-context assistant for writing, document reasoning, research, and coding.', rating: 4.7, userCount: 30000000, costTier: 'Freemium', complexityTier: 'Beginner', url: 'https://claude.ai', categories: ['writing','research','coding','document editing','productivity'], installSteps: ['Open Claude.','Sign in or create an account.','Paste or describe your task.','Iterate with examples and constraints.'] },
  { id: 'grammarly', name: 'Grammarly', description: 'Writing assistant for grammar, tone, clarity, and email/document polishing.', rating: 4.6, userCount: 30000000, costTier: 'Freemium', complexityTier: 'Beginner', url: 'https://www.grammarly.com', categories: ['writing','email management','document editing'], installSteps: ['Open Grammarly.','Install the extension or app.','Enable it where you write.','Apply suggestions selectively.'] },
  { id: 'perplexity', name: 'Perplexity', description: 'Answer engine for research, source discovery, and quick comparisons.', rating: 4.7, userCount: 15000000, costTier: 'Freemium', complexityTier: 'Beginner', url: 'https://www.perplexity.ai', categories: ['research','productivity','learning'], installSteps: ['Open Perplexity.','Ask your research question.','Review cited sources.','Refine with follow-up questions.'] },
  { id: 'canva', name: 'Canva', description: 'Design platform with AI features for graphics, presentations, social posts, and branding.', rating: 4.7, userCount: 170000000, costTier: 'Freemium', complexityTier: 'Beginner', url: 'https://www.canva.com', categories: ['design','presentation','marketing','website building'], installSteps: ['Open Canva.','Choose a template or Magic Design.','Describe the asset you need.','Customize and export.'] },
  { id: 'zapier', name: 'Zapier', description: 'No-code automation tool for connecting apps and automating repetitive workflows.', rating: 4.5, userCount: 6000000, costTier: 'Freemium', complexityTier: 'Intermediate', url: 'https://zapier.com', categories: ['automation','productivity','sales','marketing'], installSteps: ['Open Zapier.','Pick the apps to connect.','Choose a trigger and actions.','Test then turn on the Zap.'] },
  { id: 'notion-ai', name: 'Notion AI', description: 'Workspace assistant for notes, docs, summaries, planning, and knowledge organization.', rating: 4.5, userCount: 30000000, costTier: 'Paid', complexityTier: 'Beginner', url: 'https://www.notion.so/product/ai', categories: ['document editing','productivity','writing','project management'], installSteps: ['Open Notion.','Create or open a page.','Use Notion AI to draft, summarize, or organize.','Edit the result into your workspace.'] },
  { id: 'github-copilot', name: 'GitHub Copilot', description: 'AI coding assistant for completions, chat, tests, and repository work.', rating: 4.6, userCount: 15000000, costTier: 'Paid', complexityTier: 'Intermediate', url: 'https://github.com/features/copilot', categories: ['coding'], installSteps: ['Open GitHub Copilot.','Enable it for your editor.','Open your project.','Ask for code, tests, or explanations.'] }
];

const PROMPTS = { 'email management': ['Help me filter important emails', 'Draft a concise reply', 'Summarize this inbox workflow'], coding: ['Help me debug this code', 'Suggest tests for this change', 'Explain this repository workflow'], design: ['Create a design concept', 'Improve this visual asset', 'Find a tool for brand graphics'], 'document editing': ['Summarize this document', 'Improve this draft', 'Turn notes into an outline'], meetings: ['Summarize meeting notes', 'Extract action items', 'Prepare a meeting agenda'], automation: ['Automate this repetitive workflow', 'Connect these apps', 'Suggest a no-code automation'], research: ['Research this topic with sources', 'Compare tools for this task', 'Find credible references'], productivity: ['Recommend an AI productivity tool', 'Help organize this workflow', 'Find a simpler way to do this'] };
async function storageGet(keys) { return chrome.storage.sync.get(keys); }
async function storageSet(values) { return chrome.storage.sync.set(values); }
async function localSet(values) { return chrome.storage.local.set(values); }
async function localGet(keys) { return chrome.storage.local.get(keys); }
async function ensureState() { const sync = await storageGet(['savedTools', 'userPreferences']); const local = await localGet(['latestRecommendations', 'latestClassification', 'unread', 'tabDomains', 'localRecommendationCache']); return { ...DEFAULT_STATE, ...sync, ...local, userPreferences: { ...DEFAULT_STATE.userPreferences, ...(sync.userPreferences || {}) } }; }
async function userId() { const { slopUserId } = await chrome.storage.local.get('slopUserId'); if (slopUserId) return slopUserId; const id = crypto.randomUUID(); await chrome.storage.local.set({ slopUserId: id }); return id; }
async function apiBase() { return (await chrome.storage.local.get('slopApiBase')).slopApiBase || DEFAULT_API_BASE; }
async function api(path, body) { const response = await fetch(`${await apiBase()}${path}`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-user-id': await userId(), 'x-slop-token': (await chrome.storage.local.get('slopApiToken')).slopApiToken || '' }, body: JSON.stringify(body || {}) }); if (!response.ok) throw new Error((await response.json()).error || `API ${response.status}`); return response.json(); }
async function apiGet(path) { const response = await fetch(`${await apiBase()}${path}`, { headers: { 'x-user-id': await userId(), 'x-slop-token': (await chrome.storage.local.get('slopApiToken')).slopApiToken || '' } }); if (!response.ok) throw new Error(`API ${response.status}`); return response.json(); }
function topDomain(rawUrl = '') { try { return new URL(rawUrl).hostname.replace(/^www\./, ''); } catch { return ''; } }
function normalizedCacheKey(payload, category) { try { const url = new URL(payload.url); return `${url.hostname.replace(/^www\./,'')}/${url.pathname.split('/').filter(Boolean)[0] || ''}::${category}::${(payload.task || '').toLowerCase().trim()}`; } catch { return `manual::${category}::${(payload.task || '').toLowerCase().trim()}`; } }
function tier1Classify(url = '') { const normalized = url.toLowerCase(); const match = TIER1_DOMAINS.find(([pattern]) => normalized.includes(pattern)); return match && { tier: 1, taskCategory: match[1], prompts: PROMPTS[match[1]] || PROMPTS.productivity }; }
async function collectTabContext(tab) {
  let metaDescription = '';
  if (tab?.id) {
    try {
      const response = await chrome.tabs.sendMessage(tab.id, { type: 'SLOP_GET_META_DESCRIPTION' });
      metaDescription = response?.metaDescription || '';
    } catch {
      metaDescription = '';
    }
  }
  return { url: tab?.url || '', title: tab?.title || '', metaDescription };
}

function localCandidateTools(taskCategory) { return FALLBACK_TOOLS.filter(tool => tool.categories.includes(taskCategory) || tool.categories.includes('productivity')); }
function localApplyUserState(tools, taskCategory, savedTools = []) { const savedIds = new Set(savedTools.map(t => t.toolId || t.id)); return tools.map(tool => ({ ...tool, alreadySaved: savedIds.has(tool.id) && tool.categories.includes(taskCategory), fitReason: tool.fitReason || `Local fallback match for ${taskCategory}: ${tool.description}` })); }
function localApplyFilters(tools, filters = {}) { let out = [...tools]; if (filters.freeOnly) out = out.filter(t => t.costTier === 'Freemium' || t.costTier === 'Free'); if (filters.complexityTier) out = out.filter(t => t.complexityTier === filters.complexityTier); if (filters.sortBy === 'userCount') out.sort((a, b) => b.userCount - a.userCount); return out; }
function localRecommendations(payload, state) { const classification = payload.taskCategory ? { tier: 1, taskCategory: payload.taskCategory, prompts: PROMPTS[payload.taskCategory] || PROMPTS.productivity } : (payload.task ? { tier: 3, taskCategory: inferCategory(payload.task), prompts: PROMPTS[inferCategory(payload.task)] || PROMPTS.productivity } : (tier1Classify(payload.url) || { tier: 0, taskCategory: 'productivity', prompts: PROMPTS.productivity })); const ranked = localCandidateTools(classification.taskCategory).sort((a, b) => b.rating - a.rating || b.userCount - a.userCount); const personalized = localApplyFilters(localApplyUserState(ranked, classification.taskCategory, state.savedTools), state.userPreferences.defaultFilters); return { ...classification, recommendations: personalized.slice(0, 6), cacheHit: false, offlineFallback: true };
}
function inferCategory(text = '') { const lower = text.toLowerCase(); if (/email|inbox|gmail|outlook/.test(lower)) return 'email management'; if (/code|bug|github|api|test|repo|program|script/.test(lower)) return 'coding'; if (/design|figma|logo|image|brand|graphic/.test(lower)) return 'design'; if (/presentation|deck|slide/.test(lower)) return 'presentation'; if (/research|source|learn|compare|study/.test(lower)) return 'research'; if (/meeting|transcript|call|notes|agenda/.test(lower)) return 'meetings'; if (/automate|workflow|zap|integration/.test(lower)) return 'automation'; if (/spreadsheet|data|dashboard|analysis|report/.test(lower)) return 'data analysis'; if (/sales|lead|crm|pipeline/.test(lower)) return 'sales'; if (/market|campaign|social|copy/.test(lower)) return 'marketing'; if (/document|draft|write|grammar|edit|summarize/.test(lower)) return 'document editing'; return 'productivity'; }

async function requestRecommendations(payload, unread = true) { const state = await ensureState(); let result;
  try {
    result = await api('/recommendations', { ...payload, savedTools: state.savedTools });
  } catch (error) {
    result = localRecommendations(payload, state);
  } await localSet({ latestRecommendations: result.recommendations, latestClassification: { tier: result.tier, taskCategory: result.taskCategory, prompts: result.prompts, cacheHit: result.cacheHit }, unread, localRecommendationCache: { ...state.localRecommendationCache, [normalizedCacheKey(payload, result.taskCategory)]: { recommendations: result.recommendations, classification: { tier: result.tier, taskCategory: result.taskCategory, prompts: result.prompts, cacheHit: true }, cachedAt: Date.now() } } }); await emit('recommendations_shown', { taskCategory: result.taskCategory, metadata: { tier: result.tier, cacheHit: result.cacheHit } }); if (unread) await emit('notification_badge_shown', { taskCategory: result.taskCategory }); for (const tool of result.recommendations || []) if (tool.alreadySaved) await emit('saved_tool_surfaced', { toolId: tool.id, taskCategory: result.taskCategory }); return result; }
async function runAutomaticDetection(tab) { if (!tab?.id || !tab?.url || tab.url.startsWith('chrome://')) return; const state = await ensureState(); if (!state.userPreferences.privacyAcknowledged || !state.userPreferences.automaticDetectionEnabled) return; const domain = topDomain(tab.url); const previous = state.tabDomains[String(tab.id)]; if (!domain || previous === domain) return; await localSet({ tabDomains: { ...state.tabDomains, [String(tab.id)]: domain } }); setTimeout(async () => { const context = await collectTabContext(tab); await emit('detection_started', { url: context.url }); const localClassification = tier1Classify(context.url); if (localClassification) { const cached = state.localRecommendationCache[normalizedCacheKey(context, localClassification.taskCategory)]; if (cached?.recommendations?.length) { await localSet({ latestRecommendations: cached.recommendations, latestClassification: cached.classification, unread: true }); await emit('recommendations_shown', { taskCategory: localClassification.taskCategory, metadata: { tier: 1, cacheHit: true, source: 'client' } }); await emit('notification_badge_shown', { taskCategory: localClassification.taskCategory }); return; } await requestRecommendations({ ...context, ...localClassification }, true); return; } let cache = { cacheHit: false }; try { cache = await api('/cache/check', context); } catch (error) { cache = { cacheHit: false }; } if (cache.cacheHit && cache.recommendations?.length) { await localSet({ latestRecommendations: cache.recommendations, latestClassification: { tier: cache.tier, taskCategory: cache.taskCategory, prompts: cache.prompts, cacheHit: true }, unread: true }); await emit('recommendations_shown', { taskCategory: cache.taskCategory, metadata: { tier: cache.tier, cacheHit: true } }); await emit('notification_badge_shown', { taskCategory: cache.taskCategory }); return; } await requestRecommendations(context, true); }, 4000); }
async function emit(eventType, body = {}) { return api('/events', { eventType, ...body }).catch(() => undefined); }
chrome.runtime.onInstalled.addListener(async () => { const state = await ensureState(); await storageSet({ savedTools: state.savedTools, userPreferences: state.userPreferences }); });
chrome.tabs.onUpdated.addListener((_tabId, changeInfo, tab) => { if (changeInfo.status === 'complete') runAutomaticDetection(tab); });
chrome.action.onClicked.addListener(async (tab) => { if (tab?.id) chrome.tabs.sendMessage(tab.id, { type: 'SLOP_TOGGLE' }).catch(() => undefined); });
chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => { (async () => {
  if (message.type === 'SLOP_GET_STATE') return { state: await ensureState(), apiBase: await apiBase() };
  if (message.type === 'SLOP_ACK_PRIVACY') { const state = await ensureState(); const userPreferences = { ...state.userPreferences, privacyAcknowledged: true }; await storageSet({ userPreferences }); await emit('privacy_acknowledged'); return { userPreferences }; }
  if (message.type === 'SLOP_MANUAL_RECOMMEND') { await emit(message.fromPrompt ? 'suggested_prompt_submitted' : 'manual_task_submitted'); return await requestRecommendations({ task: message.task, url: message.url, title: message.title, metaDescription: message.metaDescription || '' }, false); }
  if (message.type === 'SLOP_ADVANCED_RECOMMEND') { await emit('advanced_task_submitted'); return await requestRecommendations({ task: `${message.task}\nOutcome: ${message.outcome}\nCurrent tool: ${message.currentTool}\nConstraints: ${message.constraints}`, url: message.url, title: message.title, metaDescription: message.metaDescription || '' }, false); }
  if (message.type === 'SLOP_INSTALL_GUIDE') { await emit('proceed_clicked', { toolId: message.toolId }); try { return await api('/install-guide', { toolId: message.toolId, task: message.task }); } catch (error) { const tool = FALLBACK_TOOLS.find(t => t.id === message.toolId); if (!tool) throw error; return { toolId: tool.id, toolName: tool.name, url: tool.url, steps: [...tool.installSteps, message.task ? `Use it specifically for: ${message.task}` : 'Add your task inside the tool for tailored output.', 'Return to SLOP and confirm whether you adopted the tool.'] }; } }
  if (message.type === 'SLOP_SAVE_TOOL') { const state = await ensureState(); const savedTools = [...state.savedTools.filter(t => t.toolId !== message.toolId), { toolId: message.toolId, dateAdded: new Date().toISOString(), sourceTaskCategory: message.taskCategory || 'manual' }]; await storageSet({ savedTools }); await emit('download_confirmed', { toolId: message.toolId, taskCategory: message.taskCategory }); return { savedTools }; }
  if (message.type === 'SLOP_CLEAR_SAVED') { await storageSet({ savedTools: [] }); return { savedTools: [] }; }
  if (message.type === 'SLOP_RESET_DATA') { await storageSet({ savedTools: [], userPreferences: DEFAULT_STATE.userPreferences }); await localSet({ latestRecommendations: [], latestClassification: null, unread: false, localRecommendationCache: {}, slopUserId: crypto.randomUUID() }); await emit('user_data_reset'); return { ok: true }; }
  if (message.type === 'SLOP_SET_FILTERS') { const state = await ensureState(); const userPreferences = { ...state.userPreferences, defaultFilters: message.filters || {} }; await storageSet({ userPreferences }); await emit('filter_used'); return { userPreferences }; }
  if (message.type === 'SLOP_MARK_READ') { await localSet({ unread: false }); await emit('notification_opened'); return { unread: false }; }
  if (message.type === 'SLOP_CARD_CLICKED') { await emit('card_clicked', { toolId: message.toolId }); await emit('detail_opened', { toolId: message.toolId }); if (message.alreadySaved) await emit('saved_tool_clicked', { toolId: message.toolId }); return { ok: true }; }
  if (message.type === 'SLOP_EVENT') { await emit(message.eventType, message.body || {}); return { ok: true }; }
  if (message.type === 'SLOP_SET_AUTOMATIC_DETECTION') { const state = await ensureState(); const userPreferences = { ...state.userPreferences, automaticDetectionEnabled: Boolean(message.enabled) }; await storageSet({ userPreferences }); return { userPreferences }; }
  if (message.type === 'SLOP_SET_API_BASE') { await chrome.storage.local.set({ slopApiBase: message.apiBase || DEFAULT_API_BASE }); return { apiBase: await apiBase() }; }
  if (message.type === 'SLOP_OPEN_TOOL') { await chrome.tabs.create({ url: message.url }); return { ok: true }; }
  return { error: 'Unknown message' };
})().then(sendResponse).catch(error => sendResponse({ error: error.message })); return true; });
