const rootHost = document.createElement('div');
rootHost.id = 'slop-root-host';
document.documentElement.appendChild(rootHost);
const root = rootHost.attachShadow({ mode: 'open' });
const state = { open: false, view: 'list', recommendations: [], selected: null, guide: null, task: '', prompts: [], taskCategory: '', unread: false, filters: {} };
const send = (message) => chrome.runtime.sendMessage(message);
const money = n => Intl.NumberFormat().format(n || 0);

root.innerHTML = `
<style>
:host{all:initial}.slop-bell{position:fixed;right:18px;top:45%;z-index:2147483647;width:48px;height:48px;border-radius:999px;border:1px solid rgba(255,255,255,.5);background:rgba(20,24,38,.48);color:white;backdrop-filter:blur(16px);box-shadow:0 18px 50px rgba(0,0,0,.24);cursor:pointer;font:22px system-ui}.badge{position:absolute;right:3px;top:2px;width:12px;height:12px;border-radius:999px;background:#ff4d6d;border:2px solid white}.panel{position:fixed;right:24px;top:64px;z-index:2147483647;width:min(780px,calc(100vw - 48px));height:min(620px,calc(100vh - 96px));display:none;grid-template-columns:260px 1fr;gap:14px;padding:14px;border:1px solid rgba(255,255,255,.42);border-radius:28px;background:linear-gradient(135deg,rgba(255,255,255,.28),rgba(130,150,255,.16));backdrop-filter:blur(26px) saturate(145%);box-shadow:0 24px 80px rgba(0,0,0,.35);font:14px/1.4 Inter,ui-sans-serif,system-ui;color:#f8fbff}.open{display:grid}.left,.right{overflow:auto;border-radius:22px;padding:16px;background:rgba(8,12,28,.46);border:1px solid rgba(255,255,255,.16)}h2,h3{margin:0 0 12px}.muted{color:#c7d2fe}.btn,.chip,select,input,textarea{font:inherit}.btn{border:0;border-radius:14px;padding:10px 12px;background:#8b5cf6;color:white;cursor:pointer;margin:4px 4px 4px 0}.btn.secondary{background:rgba(255,255,255,.14)}.btn.danger{background:#e11d48}.field,textarea,select{box-sizing:border-box;width:100%;border-radius:14px;border:1px solid rgba(255,255,255,.24);background:rgba(255,255,255,.1);color:white;padding:10px;margin:6px 0}.chip{display:inline-block;border:1px solid rgba(255,255,255,.24);border-radius:999px;background:rgba(255,255,255,.12);color:white;padding:7px 10px;margin:3px;cursor:pointer}.card{width:100%;text-align:left;border:1px solid rgba(255,255,255,.18);border-radius:18px;background:rgba(255,255,255,.11);color:white;margin:8px 0;padding:14px;cursor:pointer;transition:transform .22s,background .22s}.card:hover{transform:translateY(-1px);background:rgba(255,255,255,.18)}.logo{display:inline-grid;place-items:center;width:38px;height:38px;border-radius:12px;background:linear-gradient(135deg,#60a5fa,#a78bfa);font-weight:800;margin-right:10px}.row{display:flex;align-items:center;gap:8px}.detail{animation:drop .24s ease both}.steps li{margin:8px 0}.saved{color:#86efac;font-size:12px}.empty{padding:28px;text-align:center;color:#c7d2fe}@keyframes drop{from{opacity:0;transform:translateY(-8px)}to{opacity:1;transform:none}}
</style>
<button class="slop-bell" aria-label="Open SLOP">🔔<span class="badge" hidden></span></button>
<section class="panel" role="dialog" aria-label="SLOP recommendations">
  <aside class="left"><h2>SLOP</h2><p class="muted">AI tool recommendations for your current task.</p><button class="btn taskBtn">Task Input</button><button class="btn secondary advancedBtn">Advanced Search</button><div class="taskBox" hidden><textarea class="taskText" rows="3" placeholder="I need help filtering emails"></textarea><button class="btn submitTask">Get tools</button></div><h3>Suggested prompts</h3><div class="prompts"></div><h3>Filters</h3><label><input class="freeOnly" type="checkbox"> Free/freemium only</label><select class="complexity"><option value="">Any complexity</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><select class="sortBy"><option value="">Default sort</option><option value="userCount">Sort by user count</option></select><button class="btn secondary applyFilters">Apply filters</button><button class="btn danger clearSaved">Clear saved tools</button><div class="advancedBox" hidden><textarea class="advTask" rows="2" placeholder="Exact task"></textarea><input class="field advOutcome" placeholder="Desired outcome"><input class="field advTool" placeholder="Current tool, if any"><textarea class="advConstraints" rows="2" placeholder="Constraints"></textarea><button class="btn submitAdvanced">Advanced search</button></div></aside>
  <main class="right"></main>
</section>`;

const $ = sel => root.querySelector(sel);
function render() { $('.panel').classList.toggle('open', state.open); $('.badge').hidden = !state.unread; $('.prompts').innerHTML = state.prompts.map(p => `<button class="chip" data-prompt="${escapeHtml(p)}">${escapeHtml(p)}</button>`).join('') || '<p class="muted">Open a page or type a task to get prompt ideas.</p>'; const right = $('.right'); if (state.view === 'guide' && state.guide) { right.innerHTML = `<h2>${escapeHtml(state.guide.toolName)} setup</h2><ol class="steps">${state.guide.steps.map(s => `<li>${escapeHtml(s)}</li>`).join('')}</ol><button class="btn openTool">Open tool</button><button class="btn didDownload">Did you download? Yes</button><button class="btn secondary backList">Back to list</button>`; return; } if (state.view === 'detail' && state.selected) { const t = state.selected; right.innerHTML = `${cardHtml(t)}<div class="detail"><p>${escapeHtml(t.description || 'N/A')}</p><p>⭐ ${t.rating ?? 'N/A'} · Users: ${money(t.userCount) || 'N/A'} · Cost: ${t.costTier || 'N/A'} · Complexity: ${t.complexityTier || 'N/A'}</p><button class="btn proceed">Proceed</button><button class="btn secondary backList">Back to list</button></div>`; return; } right.innerHTML = `<h2>Recommendations</h2>${state.taskCategory ? `<p class="muted">Category: ${escapeHtml(state.taskCategory)}</p>` : ''}${state.recommendations.length ? state.recommendations.map(cardHtml).join('') : '<div class="empty">No recommendations yet. Use Task Input to start.</div>'}`; }
function cardHtml(t) { return `<button class="card" data-tool="${t.id}"><span class="row"><span class="logo">${escapeHtml((t.name || '?').slice(0,1))}</span><strong>${escapeHtml(t.name || 'Unknown Tool')}</strong>${t.alreadySaved ? '<span class="saved">You already use this</span>' : ''}</span></button>`; }
function escapeHtml(v) { return String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
async function refreshState() { const response = await send({ type: 'SLOP_GET_STATE' }); const s = response.state || {}; state.recommendations = s.latestRecommendations || []; state.unread = Boolean(s.unread); state.prompts = s.latestClassification?.prompts || state.prompts; state.taskCategory = s.latestClassification?.taskCategory || state.taskCategory; render(); }
async function requestManual(task) { state.task = task; const result = await send({ type: 'SLOP_MANUAL_RECOMMEND', task, url: location.href, title: document.title }); applyResult(result); }
function applyResult(result) { if (result?.error) throw new Error(result.error); state.recommendations = result.recommendations || []; state.prompts = result.prompts || []; state.taskCategory = result.taskCategory || ''; state.view = 'list'; state.open = true; state.unread = false; send({ type: 'SLOP_MARK_READ' }); render(); }

root.addEventListener('click', async (event) => { const target = event.target.closest('button'); if (!target) return; try { if (target.classList.contains('slop-bell')) { state.open = !state.open; state.unread = false; await send({ type: 'SLOP_MARK_READ' }); await refreshState(); } if (target.classList.contains('taskBtn')) $('.taskBox').hidden = !$('.taskBox').hidden; if (target.classList.contains('advancedBtn')) $('.advancedBox').hidden = !$('.advancedBox').hidden; if (target.classList.contains('submitTask')) await requestManual($('.taskText').value.trim()); if (target.dataset.prompt) { $('.taskText').value = target.dataset.prompt; await requestManual(target.dataset.prompt); } if (target.classList.contains('submitAdvanced')) applyResult(await send({ type: 'SLOP_ADVANCED_RECOMMEND', task: $('.advTask').value, outcome: $('.advOutcome').value, currentTool: $('.advTool').value, constraints: $('.advConstraints').value, url: location.href, title: document.title })); if (target.dataset.tool) { state.selected = state.recommendations.find(t => t.id === target.dataset.tool); state.view = 'detail'; render(); } if (target.classList.contains('backList')) { state.view = 'list'; render(); } if (target.classList.contains('proceed')) { state.guide = await send({ type: 'SLOP_INSTALL_GUIDE', toolId: state.selected.id, task: state.task }); state.view = 'guide'; render(); } if (target.classList.contains('openTool')) await send({ type: 'SLOP_OPEN_TOOL', url: state.guide.url }); if (target.classList.contains('didDownload')) { await send({ type: 'SLOP_SAVE_TOOL', toolId: state.guide.toolId, taskCategory: state.taskCategory }); state.view = 'list'; await refreshState(); } if (target.classList.contains('clearSaved')) await send({ type: 'SLOP_CLEAR_SAVED' }); if (target.classList.contains('applyFilters')) { state.filters = { freeOnly: $('.freeOnly').checked, complexityTier: $('.complexity').value, sortBy: $('.sortBy').value }; await send({ type: 'SLOP_SET_FILTERS', filters: state.filters }); if (state.task) await requestManual(state.task); } } catch (error) { $('.right').innerHTML = `<div class="empty">${escapeHtml(error.message)}</div>`; } });
chrome.runtime.onMessage.addListener((message) => { if (message.type === 'SLOP_TOGGLE') { state.open = !state.open; refreshState(); } });
refreshState();
