import http from 'node:http';
import { readFileSync } from 'node:fs';
import { URL } from 'node:url';
import { allowRate, cacheStats, getCache, getTools, getUsageEvents, logUsage, seedTools, setCache } from './persistence.js';
import { llmJson } from './llm.js';

const PORT = Number(process.env.PORT || 8787);
const CACHE_TTL_MS = 7 * 24 * 60 * 60 * 1000;
const TIER3_LIMIT_PER_HOUR = 20;
const API_TOKEN = process.env.SLOP_API_TOKEN || '';
const seededTools = JSON.parse(readFileSync(new URL('./tools.seed.json', import.meta.url), 'utf8'));
seedTools(seededTools);

const domainCategories = [[/mail\.google\.com|outlook\.live\.com|outlook\.office\.com/i, 'email management'], [/docs\.google\.com|office\.com|notion\.so/i, 'document editing'], [/figma\.com|canva\.com/i, 'design'], [/github\.com|gitlab\.com|stackoverflow\.com/i, 'coding'], [/calendar\.google\.com|zoom\.us|meet\.google\.com/i, 'meetings']];
function json(res, status, body) { res.writeHead(status, { 'content-type': 'application/json', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'GET,POST,OPTIONS', 'access-control-allow-headers': 'content-type,x-user-id,x-slop-token' }); res.end(JSON.stringify(body)); }
function authorized(req) { return !API_TOKEN || req.headers['x-slop-token'] === API_TOKEN; }
function readBody(req) { return new Promise((resolve) => { let data = ''; req.on('data', c => data += c); req.on('end', () => resolve(data ? JSON.parse(data) : {})); }); }
function normalize(value = '') { return value.toLowerCase().replace(/^https?:\/\//, '').replace(/[#?].*$/, '').replace(/\/$/, '').trim(); }
function domainOf(url = '') { return normalize(url).split('/')[0] || 'manual'; }
function categoryFromText(text = '') { const lower = text.toLowerCase(); if (/email|inbox|gmail|outlook/.test(lower)) return 'email management'; if (/code|bug|github|api|test|repo/.test(lower)) return 'coding'; if (/design|figma|logo|image|brand|presentation|slide/.test(lower)) return lower.includes('presentation') ? 'presentation' : 'design'; if (/research|source|learn|compare|study/.test(lower)) return 'research'; if (/meeting|transcript|call|notes/.test(lower)) return 'meetings'; if (/automate|workflow|zap|integration/.test(lower)) return 'automation'; if (/document|draft|write|grammar|edit|summarize/.test(lower)) return 'document editing'; return 'productivity'; }
function promptsFor(category) { return ({ 'email management': ['Help me filter important emails', 'Draft a concise reply', 'Summarize this inbox workflow'], coding: ['Help me debug this code', 'Suggest tests for this change', 'Explain this repository workflow'], design: ['Create a design concept', 'Improve this visual asset', 'Find a tool for brand graphics'], 'document editing': ['Summarize this document', 'Improve this draft', 'Turn notes into an outline'], meetings: ['Summarize meeting notes', 'Extract action items', 'Prepare a meeting agenda'], automation: ['Automate this repetitive workflow', 'Connect these apps', 'Suggest a no-code automation'], research: ['Research this topic with sources', 'Compare tools for this task', 'Find credible references'], productivity: ['Recommend an AI productivity tool', 'Help organize this workflow', 'Find a simpler way to do this'] })[category] || ['Recommend an AI tool', 'Help me complete this task']; }
export async function classify(payload = {}) {
  const { url = '', title = '', metaDescription = '', task = '' } = payload;
  if (task) { const taskCategory = categoryFromText(task); return { tier: 3, taskCategory, prompts: promptsFor(taskCategory) }; }
  const normalizedUrl = normalize(url);
  for (const [pattern, category] of domainCategories) if (pattern.test(normalizedUrl)) return { tier: 1, taskCategory: category, prompts: promptsFor(category) };
  return llmJson({ tier: 2, system: 'Classify a browser URL/title/meta description into one short AI-tool task category. Return JSON: {"taskCategory":"..."}.', user: JSON.stringify({ url: normalizedUrl, title, metaDescription }), fallback: () => { const taskCategory = categoryFromText(`${normalizedUrl} ${title} ${metaDescription}`); return { tier: 2, taskCategory, prompts: promptsFor(taskCategory) }; } }).then(result => ({ tier: 2, taskCategory: result.taskCategory || 'productivity', prompts: promptsFor(result.taskCategory || 'productivity') }));
}
export function cacheKey(payload, category) { const pathPattern = normalize(payload.url || 'manual').split('/').slice(0, 2).join('/'); return `${pathPattern}::${category}::${normalize(payload.task || '')}`; }
export function recommend({ taskCategory, savedTools = [], filters = {} }) { const savedIds = new Set(savedTools.map(t => t.toolId || t.id)); let ranked = getTools().filter(tool => tool.categories.includes(taskCategory) || tool.categories.includes('productivity')).sort((a, b) => Number(savedIds.has(b.id)) - Number(savedIds.has(a.id)) || b.rating - a.rating || b.userCount - a.userCount).map(tool => ({ ...tool, alreadySaved: savedIds.has(tool.id) })); if (filters.freeOnly) ranked = ranked.filter(t => t.costTier === 'Freemium' || t.costTier === 'Free'); if (filters.complexityTier) ranked = ranked.filter(t => t.complexityTier === filters.complexityTier); if (filters.sortBy === 'userCount') ranked.sort((a, b) => b.userCount - a.userCount); return ranked.slice(0, 6); }
function safeEvent(eventType, body, req) { logUsage({ eventType, domain: domainOf(body.url), taskCategory: body.taskCategory, userIdHashed: req.headers['x-user-id'] || 'anonymous', metadata: body.metadata || {} }); }
async function recommendations(body, req) { const classification = await classify(body); if (classification.tier === 3 && !allowRate(req.headers['x-user-id'] || 'anonymous', 'tier3', TIER3_LIMIT_PER_HOUR, 60 * 60 * 1000)) return { status: 429, body: { error: 'Tier 3 rate limit exceeded' } }; const key = cacheKey(body, classification.taskCategory); const cached = getCache(key); if (cached) { safeEvent('recommendations', { ...body, taskCategory: classification.taskCategory, metadata: { tier: classification.tier, cacheHit: true } }, req); return { status: 200, body: { ...cached.value, cacheHit: true } }; } const value = { ...classification, recommendations: recommend({ taskCategory: classification.taskCategory, savedTools: body.savedTools || [], filters: body.filters || {} }) }; setCache(key, value, CACHE_TTL_MS); safeEvent('recommendations', { ...body, taskCategory: classification.taskCategory, metadata: { tier: classification.tier, cacheHit: false } }, req); return { status: 200, body: { ...value, cacheHit: false } }; }
function ratio(n, d) { return d ? Number((n / d).toFixed(4)) : 0; }
function metrics() { const events = getUsageEvents(); const cache = cacheStats(); const count = type => events.filter(e => e.eventType === type).length; const shown = count('recommendations_shown') || count('recommendations'); const cardClicks = count('card_clicked'); const proceedClicks = count('proceed_clicked'); const guideCompletions = count('download_confirmed'); const cacheHits = events.filter(e => e.eventType === 'recommendations' && e.metadata?.cacheHit).length; const tier1 = events.filter(e => e.eventType === 'classify' && e.metadata?.tier === 1).length; return { cache, totalEvents: events.length, recommendationRequests: count('recommendations'), cardClicks, proceedClicks, guideCompletions, notificationOpens: count('notification_opened'), filterUses: count('filter_used'), privacyAcknowledgements: count('privacy_acknowledged'), protocolTargets: { cacheHitRate: ratio(cacheHits, count('recommendations')), tier1FreeResolutionRate: ratio(tier1, count('classify')), cardClickThroughRate: ratio(cardClicks, shown), proceedCompletionRate: ratio(guideCompletions, proceedClicks), notificationOpenRate: ratio(count('notification_opened'), count('notification_badge_shown')), filterUsageRate: ratio(count('filter_used'), shown), privacyDisclosureCompleteness: count('privacy_acknowledged') > 0 ? 1 : 0 } }; }

const server = http.createServer(async (req, res) => { if (req.method === 'OPTIONS') return json(res, 204, {}); if (!authorized(req)) return json(res, 401, { error: 'Unauthorized' }); const url = new URL(req.url, `http://${req.headers.host}`); try { if (req.method === 'GET' && url.pathname === '/health') return json(res, 200, { ok: true, cache: cacheStats(), usageEvents: getUsageEvents().length }); if (req.method === 'GET' && url.pathname === '/tools') return json(res, 200, { tools: getTools() }); if (req.method === 'GET' && (url.pathname === '/metrics' || url.pathname === '/metrics/summary')) return json(res, 200, metrics()); if (req.method === 'POST' && url.pathname === '/cache/check') { const body = await readBody(req); const classification = await classify(body); const cached = getCache(cacheKey(body, classification.taskCategory)); return json(res, 200, { cacheHit: Boolean(cached), ...classification }); } if (req.method === 'POST' && url.pathname === '/classify') { const body = await readBody(req); const result = await classify(body); safeEvent('classify', { ...body, taskCategory: result.taskCategory, metadata: { tier: result.tier } }, req); return json(res, 200, result); } if (req.method === 'POST' && url.pathname === '/recommendations') { const result = await recommendations(await readBody(req), req); return json(res, result.status, result.body); } if (req.method === 'POST' && url.pathname === '/install-guide') { const body = await readBody(req); const tool = getTools().find(t => t.id === body.toolId); if (!tool) return json(res, 404, { error: 'Unknown tool' }); safeEvent('install_guide', { ...body, taskCategory: categoryFromText(body.task || tool.categories[0]) }, req); const guide = await llmJson({ tier: 3, system: 'Return JSON {"steps":[...]} with concise numbered setup and usage guidance for an AI tool.', user: JSON.stringify({ tool, task: body.task || '' }), fallback: () => ({ steps: [...tool.installSteps, body.task ? `Use it specifically for: ${body.task}` : 'Add your task inside the tool for tailored output.', 'Return to SLOP and confirm whether you adopted the tool.'] }) }); return json(res, 200, { toolId: tool.id, toolName: tool.name, url: tool.url, steps: guide.steps }); } if (req.method === 'POST' && url.pathname === '/events') { const body = await readBody(req); safeEvent(body.eventType || 'client_event', body, req); return json(res, 202, { ok: true }); } return json(res, 404, { error: 'Not found' }); } catch (error) { return json(res, 500, { error: error.message }); } });
if (process.argv[1] && process.argv[1].endsWith('server.js')) server.listen(PORT, () => console.log(`SLOP backend listening on http://localhost:${PORT}`));
export { CACHE_TTL_MS, TIER3_LIMIT_PER_HOUR, server, seededTools as tools };
