import http from 'node:http';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { URL } from 'node:url';
import { allowRate, cacheStats, getCache, getTools, getUsageEvents, logUsage, seedTools, setCache } from './persistence.js';
import { llmJson } from './llm.js';

const PORT = Number(process.env.PORT || 8787);
const CACHE_TTL_MS = 7 * 24 * 60 * 60 * 1000;
const TIER3_LIMIT_PER_HOUR = 20;
const API_TOKEN = process.env.SLOP_API_TOKEN || '';
const HASH_SALT = process.env.SLOP_HASH_SALT || 'slop-dev-salt';
const seededTools = JSON.parse(readFileSync(new URL('./tools.seed.json', import.meta.url), 'utf8'));
const domainCategories = JSON.parse(readFileSync(new URL('./domain-categories.seed.json', import.meta.url), 'utf8'));
seedTools(seededTools);

function json(res, status, body) { res.writeHead(status, { 'content-type': 'application/json', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'GET,POST,OPTIONS', 'access-control-allow-headers': 'content-type,x-user-id,x-slop-token' }); res.end(JSON.stringify(body)); }
function authorized(req) { return !API_TOKEN || req.headers['x-slop-token'] === API_TOKEN; }
function readBody(req) { return new Promise((resolve, reject) => { let data = ''; req.on('data', c => data += c); req.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch (error) { reject(error); } }); }); }
function normalize(value = '') { return String(value).toLowerCase().replace(/^https?:\/\//, '').replace(/[#?].*$/, '').replace(/\/$/, '').trim(); }
function domainOf(url = '') { return normalize(url).split('/')[0] || 'manual'; }
function hashedUser(req) { return createHash('sha256').update(`${HASH_SALT}:${req.headers['x-user-id'] || 'anonymous'}`).digest('hex'); }
function categoryFromText(text = '') { const lower = text.toLowerCase(); if (/email|inbox|gmail|outlook/.test(lower)) return 'email management'; if (/code|bug|github|api|test|repo|program|script/.test(lower)) return 'coding'; if (/design|figma|logo|image|brand|graphic/.test(lower)) return 'design'; if (/presentation|deck|slide/.test(lower)) return 'presentation'; if (/research|source|learn|compare|study/.test(lower)) return 'research'; if (/meeting|transcript|call|notes|agenda/.test(lower)) return 'meetings'; if (/automate|workflow|zap|integration/.test(lower)) return 'automation'; if (/spreadsheet|data|dashboard|analysis|report/.test(lower)) return 'data analysis'; if (/video|clip|recording/.test(lower)) return 'video creation'; if (/sales|lead|crm|pipeline/.test(lower)) return 'sales'; if (/market|campaign|social|copy/.test(lower)) return 'marketing'; if (/document|draft|write|grammar|edit|summarize/.test(lower)) return 'document editing'; return 'productivity'; }
function promptsFor(category) { return ({ 'email management': ['Help me filter important emails', 'Draft a concise reply', 'Summarize this inbox workflow'], coding: ['Help me debug this code', 'Suggest tests for this change', 'Explain this repository workflow'], design: ['Create a design concept', 'Improve this visual asset', 'Find a tool for brand graphics'], 'document editing': ['Summarize this document', 'Improve this draft', 'Turn notes into an outline'], meetings: ['Summarize meeting notes', 'Extract action items', 'Prepare a meeting agenda'], automation: ['Automate this repetitive workflow', 'Connect these apps', 'Suggest a no-code automation'], research: ['Research this topic with sources', 'Compare tools for this task', 'Find credible references'], productivity: ['Recommend an AI productivity tool', 'Help organize this workflow', 'Find a simpler way to do this'], presentation: ['Create a presentation outline', 'Turn notes into slides', 'Improve this deck'], marketing: ['Draft campaign copy', 'Create social content ideas', 'Pick a marketing AI tool'], sales: ['Draft sales outreach', 'Summarize CRM notes', 'Find a sales assistant'], 'data analysis': ['Analyze this spreadsheet', 'Create a quick report', 'Find patterns in data'], 'video creation': ['Create an AI video', 'Edit this video workflow'] })[category] || ['Recommend an AI tool', 'Help me complete this task']; }
function tier1Classify(url = '') { const normalizedUrl = normalize(url); return domainCategories.find(row => normalizedUrl.includes(row.pattern.toLowerCase())); }
export async function classify(payload = {}, options = {}) { const { url = '', title = '', metaDescription = '', task = '', taskCategory = '' } = payload; if (taskCategory) return { tier: payload.tier || 1, taskCategory, prompts: promptsFor(taskCategory) }; if (task) { const inferred = categoryFromText(task); return { tier: 3, taskCategory: inferred, prompts: promptsFor(inferred) }; } const match = tier1Classify(url); if (match) return { tier: 1, taskCategory: match.category, prompts: match.prompts || promptsFor(match.category) }; if (options.noLlm) return { tier: null, taskCategory: null, prompts: [] }; return llmJson({ tier: 2, system: 'Classify a browser URL/title/meta description into one short AI-tool task category. Return JSON: {"taskCategory":"..."}.', user: JSON.stringify({ url: normalize(url), title, metaDescription }), fallback: () => { const inferred = categoryFromText(`${normalize(url)} ${title} ${metaDescription}`); return { taskCategory: inferred }; } }).then(result => ({ tier: 2, taskCategory: result.taskCategory || 'productivity', prompts: promptsFor(result.taskCategory || 'productivity') })); }
export function cacheKey(payload, category) { const pathPattern = normalize(payload.url || 'manual').split('/').slice(0, 2).join('/'); return `${pathPattern}::${category}::${normalize(payload.task || '')}`; }
function candidateTools(taskCategory) { return getTools().filter(tool => tool.categories.includes(taskCategory) || tool.categories.includes('productivity')).slice(0, 48); }
function applyUserState(tools, taskCategory, savedTools = []) { const savedIds = new Set(savedTools.map(t => t.toolId || t.id)); return tools.map(tool => ({ ...tool, alreadySaved: savedIds.has(tool.id) && tool.categories.includes(taskCategory) })); }
function applyClientFilters(tools, filters = {}) { let out = [...tools]; if (filters.freeOnly) out = out.filter(t => t.costTier === 'Freemium' || t.costTier === 'Free'); if (filters.complexityTier) out = out.filter(t => t.complexityTier === filters.complexityTier); if (filters.sortBy === 'userCount') out.sort((a, b) => b.userCount - a.userCount); return out; }
export function recommend({ taskCategory, savedTools = [], filters = {}, personalize = true }) { let ranked = candidateTools(taskCategory).sort((a, b) => b.rating - a.rating || b.userCount - a.userCount).slice(0, 12); if (personalize) ranked = applyUserState(ranked, taskCategory, savedTools).sort((a, b) => Number(b.alreadySaved) - Number(a.alreadySaved) || b.rating - a.rating || b.userCount - a.userCount); if (filters && Object.keys(filters).length) ranked = applyClientFilters(ranked, filters); return ranked.slice(0, 6); }
function hydrateToolIds(toolIds = []) { const byId = new Map(getTools().map(t => [t.id, t])); return [...new Set(toolIds)].map(id => byId.get(id)).filter(Boolean); }
async function generateCanonicalToolIds(body, classification) { const fallback = () => ({ toolIds: recommend({ taskCategory: classification.taskCategory, personalize: false }).map(t => t.id) }); const shouldUseLlm = classification.tier === 3 || process.env.SLOP_LLM_RECOMMEND_AUTOMATIC === 'true'; if (!shouldUseLlm) return fallback().toolIds; const result = await llmJson({ tier: classification.tier === 3 ? 3 : 2, system: 'Rank AI tools for this task. Return JSON {"toolIds":[...]} using only provided tool ids. Return canonical task-fit ranking only; do not personalize for saved tools or filters.', user: JSON.stringify({ task: body.task || '', taskCategory: classification.taskCategory, candidates: candidateTools(classification.taskCategory).map(({ id, name, description, categories, costTier, complexityTier, rating, userCount }) => ({ id, name, description, categories, costTier, complexityTier, rating, userCount })) }), fallback }); return result.toolIds || fallback().toolIds; }
function personalizeResponse(cachedOrFresh, body, classification) { const canonical = hydrateToolIds(cachedOrFresh.toolIds || cachedOrFresh.recommendations?.map(t => t.id) || []); const personalized = applyClientFilters(applyUserState(canonical, classification.taskCategory, body.savedTools || []).sort((a, b) => Number(b.alreadySaved) - Number(a.alreadySaved) || b.rating - a.rating || b.userCount - a.userCount), body.filters || {}); return { ...classification, prompts: cachedOrFresh.prompts || classification.prompts, recommendations: personalized.slice(0, 6) }; }
function safeEvent(eventType, body, req) { logUsage({ eventType, domain: domainOf(body.url), taskCategory: body.taskCategory, userIdHashed: hashedUser(req), metadata: body.metadata || {} }); }
async function recommendations(body, req) { const startedAt = Date.now(); const classification = await classify(body); if (classification.tier === 3 && !allowRate(req.headers['x-user-id'] || 'anonymous', 'tier3', TIER3_LIMIT_PER_HOUR, 60 * 60 * 1000)) return { status: 429, body: { error: 'Tier 3 rate limit exceeded' } }; const key = cacheKey(body, classification.taskCategory); const cached = getCache(key); if (cached) { safeEvent('recommendations', { ...body, taskCategory: classification.taskCategory, metadata: { tier: classification.tier, cacheHit: true, latencyMs: Date.now() - startedAt } }, req); return { status: 200, body: { ...personalizeResponse(cached.value, body, classification), cacheHit: true } }; } const value = { ...classification, toolIds: await generateCanonicalToolIds(body, classification), generatedAt: new Date().toISOString() }; setCache(key, value, CACHE_TTL_MS); safeEvent('recommendations', { ...body, taskCategory: classification.taskCategory, metadata: { tier: classification.tier, cacheHit: false, latencyMs: Date.now() - startedAt, llmCostUsd: process.env.SLOP_LLM_ENDPOINT ? (classification.tier === 3 ? 0.003 : 0.0003) : 0 } }, req); return { status: 200, body: { ...personalizeResponse(value, body, classification), cacheHit: false } }; }
function ratio(n, d) { return d ? Number((n / d).toFixed(4)) : 0; }
function metrics() { const events = getUsageEvents(); const count = type => events.filter(e => e.eventType === type).length; const recEvents = events.filter(e => e.eventType === 'recommendations'); const shown = count('recommendations_shown') || count('recommendations'); const llmSpend = events.reduce((sum, e) => sum + Number(e.metadata?.llmCostUsd || 0), 0); const users = new Set(events.map(e => e.userIdHashed).filter(Boolean)); const latencies = recEvents.map(e => Number(e.metadata?.latencyMs || 0)).filter(Boolean).sort((a,b) => a-b); const median = latencies.length ? latencies[Math.floor(latencies.length / 2)] : 0; const positive = type => events.filter(e => e.eventType === type && e.metadata?.rating === 'up').length; const feedback = type => events.filter(e => e.eventType === type).length; return { cache: cacheStats(), totalEvents: events.length, estimatedLlmSpendUsd: Number(llmSpend.toFixed(6)), dailyActiveUsersObserved: users.size, recommendationRequests: count('recommendations'), cardClicks: count('card_clicked'), proceedClicks: count('proceed_clicked'), guideCompletions: count('download_confirmed'), notificationOpens: count('notification_opened'), filterUses: count('filter_used'), privacyAcknowledgements: count('privacy_acknowledged'), protocolTargets: { llmCostPerDauDay: users.size ? Number((llmSpend / users.size).toFixed(6)) : 0, monthlySpendPerDauProjection: users.size ? Number(((llmSpend / users.size) * 30).toFixed(6)) : 0, cacheHitRate: ratio(recEvents.filter(e => e.metadata?.cacheHit).length, recEvents.length), tier1FreeResolutionRate: ratio(recEvents.filter(e => e.metadata?.tier === 1).length, recEvents.length), medianDetectionLatencyMs: median, cardClickThroughRate: ratio(count('card_clicked'), shown), detailAbandonmentRate: ratio(count('detail_abandoned'), count('detail_opened')), proceedCompletionRate: ratio(count('download_confirmed'), count('proceed_clicked')), notificationOpenRate: ratio(count('notification_opened'), count('notification_badge_shown')), filterUsageRate: ratio(count('filter_used'), shown), manualRelevantRate: ratio(positive('manual_feedback'), feedback('manual_feedback')), automaticRelevantRate: ratio(positive('automatic_feedback'), feedback('automatic_feedback')), advancedRelevantRate: ratio(positive('advanced_feedback'), feedback('advanced_feedback')), suggestedPromptUsageShare: ratio(count('suggested_prompt_submitted'), count('manual_task_submitted') + count('suggested_prompt_submitted')), advancedOutperformsAutomatic: ratio(positive('advanced_feedback'), feedback('advanced_feedback')) >= ratio(positive('automatic_feedback'), feedback('automatic_feedback')), savedToolFalsePositiveRate: ratio(count('saved_tool_dismissed'), count('saved_tool_surfaced')), privacyDisclosureCompleteness: count('privacy_acknowledged') > 0 ? 1 : 0 } }; }
function config() { return { automaticDetectionEnabled: process.env.SLOP_AUTOMATIC_DETECTION !== 'false', tier1DomainCount: domainCategories.length, domainCategories, privacyFields: ['domain', 'path', 'page title', 'meta description when explicitly available', 'typed task text', 'filters', 'saved-tool ids', 'privacy-safe usage events'] }; }

const server = http.createServer(async (req, res) => { if (req.method === 'OPTIONS') return json(res, 204, {}); if (!authorized(req)) return json(res, 401, { error: 'Unauthorized' }); const url = new URL(req.url, `http://${req.headers.host}`); try { if (req.method === 'GET' && url.pathname === '/health') return json(res, 200, { ok: true, cache: cacheStats(), usageEvents: getUsageEvents().length }); if (req.method === 'GET' && url.pathname === '/config') return json(res, 200, config()); if (req.method === 'GET' && url.pathname === '/tools') return json(res, 200, { tools: getTools() }); if (req.method === 'GET' && (url.pathname === '/metrics' || url.pathname === '/metrics/summary')) return json(res, 200, metrics()); if (req.method === 'POST' && url.pathname === '/cache/check') { const body = await readBody(req); const tier1 = await classify(body, { noLlm: true }); if (!tier1.taskCategory) return json(res, 200, { cacheHit: false, tier: null, taskCategory: null, prompts: [] }); const cached = getCache(cacheKey(body, tier1.taskCategory)); return json(res, 200, { cacheHit: Boolean(cached), ...tier1, recommendations: cached ? personalizeResponse(cached.value, body, tier1).recommendations : [] }); } if (req.method === 'POST' && url.pathname === '/classify') { const body = await readBody(req); const result = await classify(body); safeEvent('classify', { ...body, taskCategory: result.taskCategory, metadata: { tier: result.tier } }, req); return json(res, 200, result); } if (req.method === 'POST' && url.pathname === '/recommendations') { const result = await recommendations(await readBody(req), req); return json(res, result.status, result.body); } if (req.method === 'POST' && url.pathname === '/install-guide') { const body = await readBody(req); const tool = getTools().find(t => t.id === body.toolId); if (!tool) return json(res, 404, { error: 'Unknown tool' }); safeEvent('install_guide', { ...body, taskCategory: categoryFromText(body.task || tool.categories[0]) }, req); const guide = await llmJson({ tier: 3, system: 'Return JSON {"steps":[...]} with concise numbered setup and usage guidance for an AI tool.', user: JSON.stringify({ tool, task: body.task || '' }), fallback: () => ({ steps: [...tool.installSteps, body.task ? `Use it specifically for: ${body.task}` : 'Add your task inside the tool for tailored output.', 'Return to SLOP and confirm whether you adopted the tool.'] }) }); return json(res, 200, { toolId: tool.id, toolName: tool.name, url: tool.url, steps: guide.steps }); } if (req.method === 'POST' && url.pathname === '/events') { const body = await readBody(req); safeEvent(body.eventType || 'client_event', body, req); return json(res, 202, { ok: true }); } return json(res, 404, { error: 'Not found' }); } catch (error) { return json(res, 500, { error: error.message }); } });
if (process.argv[1] && process.argv[1].endsWith('server.js')) server.listen(PORT, () => console.log(`SLOP backend listening on http://localhost:${PORT}`));
export { CACHE_TTL_MS, TIER3_LIMIT_PER_HOUR, server, seededTools as tools, domainCategories };
